# This is a basic workflow to help you get started with Actions

name: Publish Wiki

# Controls when the workflow will run
on:
  gollum:
  workflow_dispatch :  
jobs:
 zip-files:
  runs-on: ubuntu-latest
  steps: 
    - name: Check out wiki
      uses: actions/checkout@v2
      with:
          repository: 'arlamaeen/testwikirepo.wiki'
          ref: 'master'
          path: 'arlamaeen/testwikirepo'  
    - name: Zip Published 
      shell: pwsh
      run: Compress-Archive -Path "arlamaeen/testwikirepo/*" -DestinationPath "user-wiki.zip" -Force
    - name: "Upload zip file"
      uses: actions/upload-artifact@v2
      with:
        name: 'user-wiki'
        path: ${{ github.workspace }}/user-wiki.zip
 publish-dev:
    if: ${{!github.event_name == 'workflow_dispatch'}}
    name: Zip and Publish to Dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Display payload
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
  #  - name: Github Wiki notifications for Teams
  #     uses: sgefdf/action-teams-gollum-notification@v1.1
  #    env:
        # A webhook URL to a Teams channel you want notifications to be sent to.
  #      WEBHOOK_URL: ${{ secrets.DEVSTACK_WEBHOOK_URL }}
    - name: Trigger pwsh
      shell: pwsh
      run: |
        write-host "Trigger mo na si push file sa dev storage"
        write-host "${{ toJSON(github.event.inputs) }}"
 publish-prod:
    if: ${{github.event_name == 'workflow_dispatch'}}
    name: Zip and Publish to Prod
    runs-on: ubuntu-latest  
    steps: 
    - name: 'Download zip files'
      uses: actions/download-artifact@v2
      with:
        name: ${{env.fileName}}
        path: ${{ github.workspace }}/
    - name : 'Upload zip to Admiral'   
      shell: pwsh
      run: |
        write-host "Trigger mo na si push file sa dev storage"
        write-host "${{ toJSON(github.event.inputs) }}"
