# This is a basic workflow to help you get started with Actions

name: On Gollum

# Controls when the workflow will run
on:
  gollum:

jobs:
  printJob:    
    name: Event gollum
    runs-on: ubuntu-latest 
    steps:
    - name: Display payload
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
